### ISSUE TITLE
Scala Native support

### ISSUE THREAD

**Issue by david-bouyssie** [takayahilton/sql-formatter#20]
Hi there.

I would like to start to work on Scala Native support.
Would you accept a PR?

**Comment by takayahilton** [comment]
@david-bouyssie 
Yes
PR of Scala Native support is welcome!

**Comment by david-bouyssie** [comment]
👍

**Comment by david-bouyssie** [comment]
Solved by PR https://github.com/takayahilton/sql-formatter/pull/23

**Comment by david-bouyssie** [comment]
I opened another issue in the vertical-blank project:
https://github.com/vertical-blank/sql-formatter/issues/17

The long-term goal is to have quill on SN.
