### ISSUE TITLE
Remove implicit ev: SqlParamable[A]

### ISSUE THREAD

**Issue by david-bouyssie** [takayahilton/sql-formatter#21]
SqlParamable is breaking the AbstractFormatter API compatibility with https://github.com/vertical-blank/scala-sql-formatter

Moreover I have the feeling that the addition of SqlParamable is not crucial, calling toString on Any type should be enough. What is the rationale behind it?

**Comment by takayahilton** [comment]
I don't intend to keep API compatibility with https://github.com/vertical-blank/scala-sql-formatter now.
Added `SqlParamable` because` Map [String, Any] `is not type safe.

**Comment by david-bouyssie** [comment]
This is a current blocker for integration with quill which is based on vertical-blank's sql-formatter . Alternatively, would you mind to expose a "formatUnsafe" API  (based on ```Map [String, Any]```) along with the current one?

**Comment by takayahilton** [comment]
@david-bouyssie  
Thank you for your suggestions.
It looks reasonable to me.
I'll add `formatUnsafe` APl  and publish it as 1.1.0.
Or would you sent PR?

**Comment by david-bouyssie** [comment]
I can make a a single PR including this and Scala Native support.
Can to do it tomorrow.

**Comment by david-bouyssie** [comment]
Solved by PR https://github.com/takayahilton/sql-formatter/pull/23
